const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS_QUERY_ID_KEY';
const GET_DETAIL_PROJECT = 'GET_DETAIL_PROJECT_QUERY_ID_KEY';
const GET_MILESTONE_PROJECTS = 'GET_MILESTONE_PROJECT_ID_KEY';
const CREATE_PROJECT = 'CREATE_PROJECT_MUTATION_ID_KEY';
const UPDATE_PROJECT = 'UPDATE_PROJECT_MUTATION_ID_KEY';
const DELETE_PROJECT = 'DELETE_PROJECT_MUTATION_ID_KEY';
const INVITE_MEMBER_TO_PROJECT = 'INVITE_MEMBER_TO_PROJECT_MUTATION_ID_KEY';
const REMOVE_MEMBER_FROM_PROJECT = 'REMOVE_MEMBER_FROM_PROJECT_MUTATION_ID_KEY';

const GET_ALL_USERS = 'GET_ALL_USERS_QUERY_ID_KEY';
const CREATE_USER = 'CREATE_USER_MUTATION_ID_KEY';
const UPDATE_USER = 'UPDATE_USER_MUTATION_ID_KEY';
const DELETE_USER = 'DELETE_USER_MUTATION_ID_KEY';
const GET_DETAIL_USER = 'GET_DETAIL_USER_QUERY_ID_KEY';
const GET_PROJECTS_USER = 'GET_PROJECTS_USER_QUERY_ID_KEY';
const GET_USER_NON_MEMBER = 'GET_USER_NON_MEMBER_QUERY_ID_KEY';

const GET_ALL_MEMBERS = 'GET_ALL_MEMBERS_QUERY_ID_KEY';
const CREATE_MEMBER = 'CREATE_MEMBER_MUTATION_ID_KEY';
const UPDATE_MEMBER = 'UPDATE_MEMBER_MUTATION_ID_KEY';
const DELETE_MEMBER = 'DELETE_MEMBER_MUTATION_ID_KEY';
const GET_DETAIL_MEMBER = 'GET_DETAIL_MEMBER_QUERY_ID_KEY';

const GET_ALL_CLIENTS = 'GET_ALL_CLIENTS_QUERY_ID_KEY';
const CREATE_CLIENT = 'CREATE_CLIENT_MUTATION_ID_KEY';
const UPDATE_CLIENT = 'UPDATE_CLIENT_MUTATION_ID_KEY';
const DELETE_CLIENT = 'DELETE_CLIENT_MUTATION_ID_KEY';
const GET_DETAIL_CLIENT = 'GET_DETAIL_CLIENT_QUERY_ID_KEY';

const GET_ALL_TASKS = 'GET_ALL_TASKS_QUERY_ID_KEY';
const GET_TASK_COMMENTS = 'GET_TASK_COMMENTS_QUERY_ID_KEY';
const SEND_TASK_COMMENT = 'SEND_TASK_COMMENT_MUTATION_ID_KEY';
const CREATE_TASK = 'CREATE_TASK_MUTATION_ID_KEY';
const UPDATE_TASK = 'UPDATE_TASK_MUTATION_ID_KEY';
const UPDATE_STATUS_TASK = 'UPDATE_STATUS_TASK_MUTATION_ID_KEY';
const DELETE_TASK = 'DELETE_TASK_MUTATION_ID_KEY';
const GET_DETAIL_TASK = 'GET_DETAIL_TASK_QUERY_ID_KEY';

const GET_ALL_MILESTONES_BY_PROJECTS =
  'GET_ALL_MILESTONESBY_PROJECT_QUERY_ID_KEY';
const GET_ALL_MILESTONES = 'GET_ALL_MILESTONESBY_QUERY_ID_KEY';
const GET_MILESTONE_DETAIL = 'GET_MILESTONE_DETAIL_QUERY_ID_KEY';
const CREATE_MILESTONES_ON_PROJECT =
  'CREATE_MILESTONE_ON_PROJECT_MUTATION_ID_KEY';

const GET_USER_CREDENTIALS = 'GET_USER_CREDENTIALS_QUERY_ID_KEY';
const LOGIN_AUTH = 'LOGIN_AUTH_MUTATION_ID_KEY';

const GET_ALL_PAYROLLS = 'GET_ALL_PAYROLLS_QUERY_ID_KEY';
const CREATE_PAYROLL = 'CREATE_PAYROLL_MUTATION_ID_KEY';
const UPDATE_PAYROLL = 'UPDATE_PAYROLL_MUTATION_ID_KEY';
const DELETE_PAYROLL = 'DELETE_PAYROLL_MUTATION_ID_KEY';
const GET_DETAIL_PAYROLL = 'GET_DETAIL_PAYROLL_QUERY_ID_KEY';
const GET_PAYROLL_MEMBER = 'GET_MEMBER_PAYROLL_QUERY_ID_KEY';
const GET_MEMBER_NON_PAYROLL = 'GET_MEMBER_NON_PAYROLL_QUERY_ID_KEY';

const GET_USER_PROFILE = 'GET_USER_PROFILE_QUERY_ID_KEY';
const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE_MUTATION_ID_KEY';
const UPDATE_PROFILE = 'UPDATE_PROFILE_MUTATION_ID_KEY';

const GET_MEMBER_PROJECT_MANAGER = 'GET_MEMBER_PROJECT_MANAGER_QUERY_ID_KEY';

export {
  GET_USER_CREDENTIALS,
  UPDATE_PROFILE_PICTURE,
  GET_PAYROLL_MEMBER,
  GET_MEMBER_NON_PAYROLL,
  UPDATE_PROFILE,
  GET_USER_PROFILE,
  LOGIN_AUTH,
  GET_ALL_PROJECTS,
  GET_DETAIL_PROJECT,
  GET_MILESTONE_PROJECTS,
  GET_MEMBER_PROJECT_MANAGER,
  GET_USER_NON_MEMBER,
  CREATE_PROJECT,
  UPDATE_PROJECT,
  DELETE_PROJECT,
  INVITE_MEMBER_TO_PROJECT,
  REMOVE_MEMBER_FROM_PROJECT,
  GET_ALL_USERS,
  GET_DETAIL_USER,
  GET_PROJECTS_USER,
  GET_ALL_MILESTONES,
  CREATE_USER,
  UPDATE_USER,
  DELETE_USER,
  GET_ALL_MEMBERS,
  GET_DETAIL_MEMBER,
  CREATE_MEMBER,
  UPDATE_MEMBER,
  DELETE_MEMBER,
  GET_ALL_PAYROLLS,
  GET_DETAIL_PAYROLL,
  CREATE_PAYROLL,
  UPDATE_PAYROLL,
  DELETE_PAYROLL,
  GET_ALL_CLIENTS,
  GET_DETAIL_CLIENT,
  CREATE_CLIENT,
  UPDATE_CLIENT,
  DELETE_CLIENT,
  GET_ALL_TASKS,
  GET_DETAIL_TASK,
  SEND_TASK_COMMENT,
  GET_TASK_COMMENTS,
  CREATE_TASK,
  UPDATE_TASK,
  UPDATE_STATUS_TASK,
  DELETE_TASK,
  GET_ALL_MILESTONES_BY_PROJECTS,
  CREATE_MILESTONES_ON_PROJECT,
  GET_MILESTONE_DETAIL,
};
