const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS_QUERY_ID_KEY';
const GET_DETAIL_PROJECT = 'GET_DETAIL_PROJECT_QUERY_ID_KEY';
const GET_MILESTONE_PROJECTS = 'GET_MILESTONE_PROJECT_ID_KEY';

export { GET_ALL_PROJECTS, GET_DETAIL_PROJECT, GET_MILESTONE_PROJECTS };
